This file uploads, cleans and explains the used data

Sources : 
https://www.services-rte.com/fr/visualisez-les-donnees-publiees-par-rte/bourses-de-lelectricite-spot-france.html
https://transparency.entsoe.eu/market/energyPrices?appState=%7B%22sa%22%3A%5B%22BZN%7C10YFR-RTE------C%22%5D%2C%22st%22%3A%22BZN%22%2C%22mm%22%3Afalse%2C%22ma%22%3Afalse%2C%22sp%22%3A%22HALF%22%2C%22dt%22%3A%22TABLE%22%2C%22df%22%3A%222026-01-01%22%2C%22tz%22%3A%22WET%22%7D

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv("Data/raw/France sdac.csv")

In [39]:
df

      MTU (WET/WEST);Area;Sequence;Day-ahead Price (EUR/MWh);Intraday Period (WET/WEST);Intraday Price (EUR/MWh)
0      01/01/2026 00:00:00 - 01/01/2026 00:15:00,"BZN...
1      01/01/2026 00:15:00 - 01/01/2026 00:30:00,"BZN...
2      01/01/2026 00:30:00 - 01/01/2026 00:45:00,"BZN...
3      01/01/2026 00:45:00 - 01/01/2026 01:00:00,"BZN...
4      01/01/2026 01:00:00 - 01/01/2026 01:15:00,"BZN...
...                                                  ...
11891  04/05/2026 21:45:00 - 04/05/2026 22:00:00,"BZN...
11892  04/05/2026 22:00:00 - 04/05/2026 22:15:00,"BZN...
11893  04/05/2026 22:15:00 - 04/05/2026 22:30:00,"BZN...
11894  04/05/2026 22:30:00 - 04/05/2026 22:45:00,"BZN...
11895  04/05/2026 22:45:00 - 04/05/2026 23:00:00,"BZN...

[11896 rows x 1 columns]

In [40]:
df.columns = df.columns.str.replace(";", ",")

In [41]:
df.head()

  MTU (WET/WEST),Area,Sequence,Day-ahead Price (EUR/MWh),Intraday Period (WET/WEST),Intraday Price (EUR/MWh)
0  01/01/2026 00:00:00 - 01/01/2026 00:15:00,"BZN...
1  01/01/2026 00:15:00 - 01/01/2026 00:30:00,"BZN...
2  01/01/2026 00:30:00 - 01/01/2026 00:45:00,"BZN...
3  01/01/2026 00:45:00 - 01/01/2026 01:00:00,"BZN...
4  01/01/2026 01:00:00 - 01/01/2026 01:15:00,"BZN...

In [42]:
df = df.iloc[:, 0].str.split(",", expand=True)

In [43]:
df

,0,1,2,3,4,5
0,01/01/2026 00:00:00 - 01/01/2026 00:15:00,"""BZN|FR""","""Without Sequence""","""78.11""","""""",""""";;;;;"
1,01/01/2026 00:15:00 - 01/01/2026 00:30:00,"""BZN|FR""","""Without Sequence""","""68.99""","""""",""""";;;;;"
2,01/01/2026 00:30:00 - 01/01/2026 00:45:00,"""BZN|FR""","""Without Sequence""","""69.75""","""""",""""";;;;/;"
3,01/01/2026 00:45:00 - 01/01/2026 01:00:00,"""BZN|FR""","""Without Sequence""","""58.72""","""""",""""";;;;;"
4,01/01/2026 01:00:00 - 01/01/2026 01:15:00,"""BZN|FR""","""Without Sequence""","""72.94""","""""",""""";;;;;"
...,...,...,...,...,...,...
11891,04/05/2026 21:45:00 - 04/05/2026 22:00:00,"""BZN|FR""","""Without Sequence""","""130.86""","""""",""""";;;;;"
11892,04/05/2026 22:00:00 - 04/05/2026 22:15:00,"""BZN|FR""","""Without Sequence""","""136.61""","""""",""""";;;;;"
11893,04/05/2026 22:15:00 - 04/05/2026 22:30:00,"""BZN|FR""","""Without Sequence""","""122.01""","""""",""""";;;;;"
11894,04/05/2026 22:30:00 - 04/05/2026 22:45:00,"""BZN|FR""","""Without Sequence""","""119.78""","""""",""""";;;;;"
11895,04/05/2026 22:45:00 - 04/05/2026 23:00:00,"""BZN|FR""","""Without Sequence""","""111.00""","""""",""""";;;;;"

In [44]:
df.columns = ["MTU", "Area", "Sequence", "Day-ahead Price (EUR/MWh)", "Intraday Period", "Intraday Price (EUR/MWh)"]
df.head()

,MTU,Area,Sequence,Day-ahead Price (EUR/MWh),Intraday Period,Intraday Price (EUR/MWh)
0,01/01/2026 00:00:00 - 01/01/2026 00:15:00,"""BZN|FR""","""Without Sequence""","""78.11""","""""",""""";;;;;"
1,01/01/2026 00:15:00 - 01/01/2026 00:30:00,"""BZN|FR""","""Without Sequence""","""68.99""","""""",""""";;;;;"
2,01/01/2026 00:30:00 - 01/01/2026 00:45:00,"""BZN|FR""","""Without Sequence""","""69.75""","""""",""""";;;;/;"
3,01/01/2026 00:45:00 - 01/01/2026 01:00:00,"""BZN|FR""","""Without Sequence""","""58.72""","""""",""""";;;;;"
4,01/01/2026 01:00:00 - 01/01/2026 01:15:00,"""BZN|FR""","""Without Sequence""","""72.94""","""""",""""";;;;;"

In [45]:
df = df.drop(columns=["Area", "Sequence", "Intraday Period", "Intraday Price (EUR/MWh)"])
df

                                             MTU Day-ahead Price (EUR/MWh)
0      01/01/2026 00:00:00 - 01/01/2026 00:15:00                   "78.11"
1      01/01/2026 00:15:00 - 01/01/2026 00:30:00                   "68.99"
2      01/01/2026 00:30:00 - 01/01/2026 00:45:00                   "69.75"
3      01/01/2026 00:45:00 - 01/01/2026 01:00:00                   "58.72"
4      01/01/2026 01:00:00 - 01/01/2026 01:15:00                   "72.94"
...                                          ...                       ...
11891  04/05/2026 21:45:00 - 04/05/2026 22:00:00                  "130.86"
11892  04/05/2026 22:00:00 - 04/05/2026 22:15:00                  "136.61"
11893  04/05/2026 22:15:00 - 04/05/2026 22:30:00                  "122.01"
11894  04/05/2026 22:30:00 - 04/05/2026 22:45:00                  "119.78"
11895  04/05/2026 22:45:00 - 04/05/2026 23:00:00                  "111.00"

[11896 rows x 2 columns]

In [46]:
df.iloc[:, 1] = df.iloc[:, 1].str.replace('"', '')
df.head()

                                         MTU Day-ahead Price (EUR/MWh)
0  01/01/2026 00:00:00 - 01/01/2026 00:15:00                     78.11
1  01/01/2026 00:15:00 - 01/01/2026 00:30:00                     68.99
2  01/01/2026 00:30:00 - 01/01/2026 00:45:00                     69.75
3  01/01/2026 00:45:00 - 01/01/2026 01:00:00                     58.72
4  01/01/2026 01:00:00 - 01/01/2026 01:15:00                     72.94

In [47]:
df2 = pd.read_csv('Data/raw/FrGen26.csv')  
print(df2.head(10))

  MTU (UTC),"Area","Production Type","Generation (MW)"
0  01/01/2026 00:00:00 - 01/01/2026 00:15:00,"BZN...
1  01/01/2026 00:15:00 - 01/01/2026 00:30:00,"BZN...
2  01/01/2026 00:30:00 - 01/01/2026 00:45:00,"BZN...
3  01/01/2026 00:45:00 - 01/01/2026 01:00:00,"BZN...
4  01/01/2026 01:00:00 - 01/01/2026 01:15:00,"BZN...
5  01/01/2026 01:15:00 - 01/01/2026 01:30:00,"BZN...
6  01/01/2026 01:30:00 - 01/01/2026 01:45:00,"BZN...
7  01/01/2026 01:45:00 - 01/01/2026 02:00:00,"BZN...
8  01/01/2026 02:00:00 - 01/01/2026 02:15:00,"BZN...
9  01/01/2026 02:15:00 - 01/01/2026 02:30:00,"BZN...

In [48]:
df2 = df2.iloc[:, 0].str.split(",", expand=True)
df2.head()

                                           0         1          2      3
0  01/01/2026 00:00:00 - 01/01/2026 00:15:00  "BZN|FR"  "Biomass"  "N/A"
1  01/01/2026 00:15:00 - 01/01/2026 00:30:00  "BZN|FR"  "Biomass"  "N/A"
2  01/01/2026 00:30:00 - 01/01/2026 00:45:00  "BZN|FR"  "Biomass"  "N/A"
3  01/01/2026 00:45:00 - 01/01/2026 01:00:00  "BZN|FR"  "Biomass"  "N/A"
4  01/01/2026 01:00:00 - 01/01/2026 01:15:00  "BZN|FR"  "Biomass"  "N/A"

In [49]:
df2.columns = ["MTU", "Area", "Type", "MW"] 
df2.head()

                                         MTU      Area       Type     MW
0  01/01/2026 00:00:00 - 01/01/2026 00:15:00  "BZN|FR"  "Biomass"  "N/A"
1  01/01/2026 00:15:00 - 01/01/2026 00:30:00  "BZN|FR"  "Biomass"  "N/A"
2  01/01/2026 00:30:00 - 01/01/2026 00:45:00  "BZN|FR"  "Biomass"  "N/A"
3  01/01/2026 00:45:00 - 01/01/2026 01:00:00  "BZN|FR"  "Biomass"  "N/A"
4  01/01/2026 01:00:00 - 01/01/2026 01:15:00  "BZN|FR"  "Biomass"  "N/A"

In [50]:
print("ALL production types:")
print(df2['Type'].value_counts())

ALL production types:
Type
"Biomass"                           35040
"Hydro Run-of-river and pondage"    35040
"Wind Offshore"                     35040
"Waste"                             35040
"Solar"                             35040
"Other renewable"                   35040
"Other"                             35040
"Nuclear"                           35040
"Marine"                            35040
"Hydro Water Reservoir"             35040
"Hydro Pumped Storage"              35040
"Energy storage"                    35040
"Geothermal"                        35040
"Fossil Peat"                       35040
"Fossil Oil shale"                  35040
"Fossil Oil"                        35040
"Fossil Hard coal"                  35040
"Fossil Gas"                        35040
"Fossil Coal-derived gas"           35040
"Fossil Brown coal/Lignite"         35040
"Wind Onshore"                      35040
Name: count, dtype: int64

In [51]:
df2['Type'] = df2['Type'].str.strip('"\' ')
df2

,MTU,Area,Type,MW
0,01/01/2026 00:00:00 - 01/01/2026 00:15:00,"""BZN|FR""",Biomass,"""N/A"""
1,01/01/2026 00:15:00 - 01/01/2026 00:30:00,"""BZN|FR""",Biomass,"""N/A"""
2,01/01/2026 00:30:00 - 01/01/2026 00:45:00,"""BZN|FR""",Biomass,"""N/A"""
3,01/01/2026 00:45:00 - 01/01/2026 01:00:00,"""BZN|FR""",Biomass,"""N/A"""
4,01/01/2026 01:00:00 - 01/01/2026 01:15:00,"""BZN|FR""",Biomass,"""N/A"""
...,...,...,...,...
735835,31/12/2026 22:45:00 - 31/12/2026 23:00:00,"""BZN|FR""",Wind Onshore,"""-"""
735836,31/12/2026 23:00:00 - 31/12/2026 23:15:00,"""BZN|FR""",Wind Onshore,"""-"""
735837,31/12/2026 23:15:00 - 31/12/2026 23:30:00,"""BZN|FR""",Wind Onshore,"""-"""
735838,31/12/2026 23:30:00 - 31/12/2026 23:45:00,"""BZN|FR""",Wind Onshore,"""-"""
735839,31/12/2026 23:45:00 - 01/01/2027 00:00:00,"""BZN|FR""",Wind Onshore,"""-"""